// soc_system_sld_hub_controller_system_0_link_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module soc_system_sld_hub_controller_system_0_link_mm_interconnect_2 (
		input  wire        clock_bridge_out_clk_clk,                                //                              clock_bridge_out_clk.clk
		input  wire        read_slave_addr_fixer_reset_reset_bridge_in_reset_reset, // read_slave_addr_fixer_reset_reset_bridge_in_reset.reset
		input  wire [2:0]  read_slave_addr_fixer_m0_address,                        //                          read_slave_addr_fixer_m0.address
		output wire        read_slave_addr_fixer_m0_waitrequest,                    //                                                  .waitrequest
		input  wire        read_slave_addr_fixer_m0_read,                           //                                                  .read
		output wire [31:0] read_slave_addr_fixer_m0_readdata,                       //                                                  .readdata
		input  wire        read_slave_addr_fixer_m0_write,                          //                                                  .write
		input  wire [31:0] read_slave_addr_fixer_m0_writedata,                      //                                                  .writedata
		output wire [0:0]  sink_to_read_slave_out_address,                          //                            sink_to_read_slave_out.address
		output wire        sink_to_read_slave_out_read,                             //                                                  .read
		input  wire [31:0] sink_to_read_slave_out_readdata,                         //                                                  .readdata
		input  wire        sink_to_read_slave_out_waitrequest                       //                                                  .waitrequest
	);

	wire         read_slave_addr_fixer_m0_translator_avalon_universal_master_0_waitrequest;   // sink_to_read_slave_out_translator:uav_waitrequest -> read_slave_addr_fixer_m0_translator:uav_waitrequest
	wire  [31:0] read_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdata;      // sink_to_read_slave_out_translator:uav_readdata -> read_slave_addr_fixer_m0_translator:uav_readdata
	wire         read_slave_addr_fixer_m0_translator_avalon_universal_master_0_debugaccess;   // read_slave_addr_fixer_m0_translator:uav_debugaccess -> sink_to_read_slave_out_translator:uav_debugaccess
	wire   [2:0] read_slave_addr_fixer_m0_translator_avalon_universal_master_0_address;       // read_slave_addr_fixer_m0_translator:uav_address -> sink_to_read_slave_out_translator:uav_address
	wire         read_slave_addr_fixer_m0_translator_avalon_universal_master_0_read;          // read_slave_addr_fixer_m0_translator:uav_read -> sink_to_read_slave_out_translator:uav_read
	wire   [3:0] read_slave_addr_fixer_m0_translator_avalon_universal_master_0_byteenable;    // read_slave_addr_fixer_m0_translator:uav_byteenable -> sink_to_read_slave_out_translator:uav_byteenable
	wire         read_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdatavalid; // sink_to_read_slave_out_translator:uav_readdatavalid -> read_slave_addr_fixer_m0_translator:uav_readdatavalid
	wire         read_slave_addr_fixer_m0_translator_avalon_universal_master_0_lock;          // read_slave_addr_fixer_m0_translator:uav_lock -> sink_to_read_slave_out_translator:uav_lock
	wire         read_slave_addr_fixer_m0_translator_avalon_universal_master_0_write;         // read_slave_addr_fixer_m0_translator:uav_write -> sink_to_read_slave_out_translator:uav_write
	wire  [31:0] read_slave_addr_fixer_m0_translator_avalon_universal_master_0_writedata;     // read_slave_addr_fixer_m0_translator:uav_writedata -> sink_to_read_slave_out_translator:uav_writedata
	wire   [2:0] read_slave_addr_fixer_m0_translator_avalon_universal_master_0_burstcount;    // read_slave_addr_fixer_m0_translator:uav_burstcount -> sink_to_read_slave_out_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (3),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (3),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) read_slave_addr_fixer_m0_translator (
		.clk                    (clock_bridge_out_clk_clk),                                                    //                       clk.clk
		.reset                  (read_slave_addr_fixer_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (read_slave_addr_fixer_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (read_slave_addr_fixer_m0_waitrequest),                                        //                          .waitrequest
		.av_read                (read_slave_addr_fixer_m0_read),                                               //                          .read
		.av_readdata            (read_slave_addr_fixer_m0_readdata),                                           //                          .readdata
		.av_write               (read_slave_addr_fixer_m0_write),                                              //                          .write
		.av_writedata           (read_slave_addr_fixer_m0_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                        //               (terminated)
		.av_byteenable          (4'b1111),                                                                     //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                        //               (terminated)
		.av_begintransfer       (1'b0),                                                                        //               (terminated)
		.av_chipselect          (1'b0),                                                                        //               (terminated)
		.av_readdatavalid       (),                                                                            //               (terminated)
		.av_lock                (1'b0),                                                                        //               (terminated)
		.av_debugaccess         (1'b0),                                                                        //               (terminated)
		.uav_clken              (),                                                                            //               (terminated)
		.av_clken               (1'b1),                                                                        //               (terminated)
		.uav_response           (2'b00),                                                                       //               (terminated)
		.av_response            (),                                                                            //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                        //               (terminated)
		.av_writeresponsevalid  ()                                                                             //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (3),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) sink_to_read_slave_out_translator (
		.clk                    (clock_bridge_out_clk_clk),                                                    //                      clk.clk
		.reset                  (read_slave_addr_fixer_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (read_slave_addr_fixer_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (sink_to_read_slave_out_address),                                              //      avalon_anti_slave_0.address
		.av_read                (sink_to_read_slave_out_read),                                                 //                         .read
		.av_readdata            (sink_to_read_slave_out_readdata),                                             //                         .readdata
		.av_waitrequest         (sink_to_read_slave_out_waitrequest),                                          //                         .waitrequest
		.av_write               (),                                                                            //              (terminated)
		.av_writedata           (),                                                                            //              (terminated)
		.av_begintransfer       (),                                                                            //              (terminated)
		.av_beginbursttransfer  (),                                                                            //              (terminated)
		.av_burstcount          (),                                                                            //              (terminated)
		.av_byteenable          (),                                                                            //              (terminated)
		.av_readdatavalid       (1'b0),                                                                        //              (terminated)
		.av_writebyteenable     (),                                                                            //              (terminated)
		.av_lock                (),                                                                            //              (terminated)
		.av_chipselect          (),                                                                            //              (terminated)
		.av_clken               (),                                                                            //              (terminated)
		.uav_clken              (1'b0),                                                                        //              (terminated)
		.av_debugaccess         (),                                                                            //              (terminated)
		.av_outputenable        (),                                                                            //              (terminated)
		.uav_response           (),                                                                            //              (terminated)
		.av_response            (2'b00),                                                                       //              (terminated)
		.uav_writeresponsevalid (),                                                                            //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                         //              (terminated)
	);

endmodule
