// soc_system_sld_hub_controller_system_0_fabric.v

// This file was auto-generated from altera_debug_fabric_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module soc_system_sld_hub_controller_system_0_fabric (
		input  wire       clk_clk,             //     clk.clk
		input  wire       reset_reset,         //   reset.reset
		output wire       h2t_ready,           //     h2t.ready
		input  wire       h2t_valid,           //        .valid
		input  wire [7:0] h2t_data,            //        .data
		input  wire       h2t_startofpacket,   //        .startofpacket
		input  wire       h2t_endofpacket,     //        .endofpacket
		input  wire [0:0] h2t_channel,         //        .channel
		input  wire       t2h_ready,           //     t2h.ready
		output wire       t2h_valid,           //        .valid
		output wire [7:0] t2h_data,            //        .data
		output wire       t2h_startofpacket,   //        .startofpacket
		output wire       t2h_endofpacket,     //        .endofpacket
		output wire [0:0] t2h_channel,         //        .channel
		input  wire       mgmt_valid,          //    mgmt.valid
		input  wire       mgmt_data,           //        .data
		input  wire [0:0] mgmt_channel,        //        .channel
		output wire       reset_0_reset,       // reset_0.reset
		input  wire       h2t_0_ready,         //   h2t_0.ready
		output wire       h2t_0_valid,         //        .valid
		output wire [7:0] h2t_0_data,          //        .data
		output wire       h2t_0_startofpacket, //        .startofpacket
		output wire       h2t_0_endofpacket,   //        .endofpacket
		output wire       t2h_0_ready,         //   t2h_0.ready
		input  wire       t2h_0_valid,         //        .valid
		input  wire [7:0] t2h_0_data,          //        .data
		input  wire       t2h_0_startofpacket, //        .startofpacket
		input  wire       t2h_0_endofpacket    //        .endofpacket
	);

	wire        mgmt_time_adap_out_valid;   // mgmt_time_adap:out_valid -> mgmt_demux:in_valid
	wire        mgmt_time_adap_out_data;    // mgmt_time_adap:out_data -> mgmt_demux:in_data
	wire        mgmt_time_adap_out_ready;   // mgmt_demux:in_ready -> mgmt_time_adap:out_ready
	wire        mgmt_time_adap_out_channel; // mgmt_time_adap:out_channel -> mgmt_demux:in_channel
	wire        demux_out0_valid;           // demux:out0_valid -> mux:in0_valid
	wire  [7:0] demux_out0_data;            // demux:out0_data -> mux:in0_data
	wire        demux_out0_ready;           // mux:in0_ready -> demux:out0_ready
	wire        demux_out0_startofpacket;   // demux:out0_startofpacket -> mux:in0_startofpacket
	wire        demux_out0_endofpacket;     // demux:out0_endofpacket -> mux:in0_endofpacket
	wire        mgmt_demux_out1_valid;      // mgmt_demux:out1_valid -> mgmt_reset_0:mgmt_valid
	wire        mgmt_demux_out1_data;       // mgmt_demux:out1_data -> mgmt_reset_0:mgmt_data
	wire        mgmt_demux_out1_ready;      // mgmt_reset_0:mgmt_ready -> mgmt_demux:out1_ready

	soc_system_sld_hub_controller_system_0_fabric_demux demux (
		.clk                (clk_clk),                  //   clk.clk
		.reset_n            (~reset_reset),             // reset.reset_n
		.in_data            (h2t_data),                 //    in.data
		.in_valid           (h2t_valid),                //      .valid
		.in_ready           (h2t_ready),                //      .ready
		.in_startofpacket   (h2t_startofpacket),        //      .startofpacket
		.in_endofpacket     (h2t_endofpacket),          //      .endofpacket
		.in_channel         (h2t_channel),              //      .channel
		.out0_data          (demux_out0_data),          //  out0.data
		.out0_valid         (demux_out0_valid),         //      .valid
		.out0_ready         (demux_out0_ready),         //      .ready
		.out0_startofpacket (demux_out0_startofpacket), //      .startofpacket
		.out0_endofpacket   (demux_out0_endofpacket),   //      .endofpacket
		.out1_data          (h2t_0_data),               //  out1.data
		.out1_valid         (h2t_0_valid),              //      .valid
		.out1_ready         (h2t_0_ready),              //      .ready
		.out1_startofpacket (h2t_0_startofpacket),      //      .startofpacket
		.out1_endofpacket   (h2t_0_endofpacket)         //      .endofpacket
	);

	soc_system_sld_hub_controller_system_0_fabric_mux mux (
		.clk               (clk_clk),                  //   clk.clk
		.reset_n           (~reset_reset),             // reset.reset_n
		.out_data          (t2h_data),                 //   out.data
		.out_valid         (t2h_valid),                //      .valid
		.out_ready         (t2h_ready),                //      .ready
		.out_startofpacket (t2h_startofpacket),        //      .startofpacket
		.out_endofpacket   (t2h_endofpacket),          //      .endofpacket
		.out_channel       (t2h_channel),              //      .channel
		.in0_data          (demux_out0_data),          //   in0.data
		.in0_valid         (demux_out0_valid),         //      .valid
		.in0_ready         (demux_out0_ready),         //      .ready
		.in0_startofpacket (demux_out0_startofpacket), //      .startofpacket
		.in0_endofpacket   (demux_out0_endofpacket),   //      .endofpacket
		.in1_data          (t2h_0_data),               //   in1.data
		.in1_valid         (t2h_0_valid),              //      .valid
		.in1_ready         (t2h_0_ready),              //      .ready
		.in1_startofpacket (t2h_0_startofpacket),      //      .startofpacket
		.in1_endofpacket   (t2h_0_endofpacket)         //      .endofpacket
	);

	soc_system_sld_hub_controller_system_0_fabric_mgmt_demux mgmt_demux (
		.clk        (clk_clk),                    //   clk.clk
		.reset_n    (~reset_reset),               // reset.reset_n
		.in_data    (mgmt_time_adap_out_data),    //    in.data
		.in_valid   (mgmt_time_adap_out_valid),   //      .valid
		.in_ready   (mgmt_time_adap_out_ready),   //      .ready
		.in_channel (mgmt_time_adap_out_channel), //      .channel
		.out0_data  (),                           //  out0.data
		.out0_valid (),                           //      .valid
		.out0_ready (1'b1),                       //      .ready
		.out1_data  (mgmt_demux_out1_data),       //  out1.data
		.out1_valid (mgmt_demux_out1_valid),      //      .valid
		.out1_ready (mgmt_demux_out1_ready)       //      .ready
	);

	soc_system_sld_hub_controller_system_0_fabric_mgmt_time_adap mgmt_time_adap (
		.clk         (clk_clk),                    //   clk.clk
		.reset_n     (~reset_reset),               // reset.reset_n
		.in_data     (mgmt_data),                  //    in.data
		.in_valid    (mgmt_valid),                 //      .valid
		.in_channel  (mgmt_channel),               //      .channel
		.out_data    (mgmt_time_adap_out_data),    //   out.data
		.out_valid   (mgmt_time_adap_out_valid),   //      .valid
		.out_ready   (mgmt_time_adap_out_ready),   //      .ready
		.out_channel (mgmt_time_adap_out_channel)  //      .channel
	);

	altera_mgmt_reset mgmt_reset_0 (
		.clk         (clk_clk),               //          clk.clk
		.reset       (reset_reset),           //        reset.reset
		.mgmt_data   (mgmt_demux_out1_data),  //         mgmt.data
		.mgmt_valid  (mgmt_demux_out1_valid), //             .valid
		.mgmt_ready  (mgmt_demux_out1_ready), //             .ready
		.agent_reset (reset_0_reset)          // reset_source.reset
	);

endmodule
