// soc_system_sld_hub_controller_system_0_link_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module soc_system_sld_hub_controller_system_0_link_mm_interconnect_1 (
		input  wire        clock_bridge_out_clk_clk,                                 //                               clock_bridge_out_clk.clk
		input  wire        write_slave_addr_fixer_reset_reset_bridge_in_reset_reset, // write_slave_addr_fixer_reset_reset_bridge_in_reset.reset
		input  wire [2:0]  write_slave_addr_fixer_m0_address,                        //                          write_slave_addr_fixer_m0.address
		output wire        write_slave_addr_fixer_m0_waitrequest,                    //                                                   .waitrequest
		input  wire        write_slave_addr_fixer_m0_read,                           //                                                   .read
		output wire [31:0] write_slave_addr_fixer_m0_readdata,                       //                                                   .readdata
		input  wire        write_slave_addr_fixer_m0_write,                          //                                                   .write
		input  wire [31:0] write_slave_addr_fixer_m0_writedata,                      //                                                   .writedata
		output wire [0:0]  write_slave_to_source_in_address,                         //                           write_slave_to_source_in.address
		output wire        write_slave_to_source_in_write,                           //                                                   .write
		output wire [31:0] write_slave_to_source_in_writedata,                       //                                                   .writedata
		input  wire        write_slave_to_source_in_waitrequest                      //                                                   .waitrequest
	);

	wire         write_slave_addr_fixer_m0_translator_avalon_universal_master_0_waitrequest;   // write_slave_to_source_in_translator:uav_waitrequest -> write_slave_addr_fixer_m0_translator:uav_waitrequest
	wire  [31:0] write_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdata;      // write_slave_to_source_in_translator:uav_readdata -> write_slave_addr_fixer_m0_translator:uav_readdata
	wire         write_slave_addr_fixer_m0_translator_avalon_universal_master_0_debugaccess;   // write_slave_addr_fixer_m0_translator:uav_debugaccess -> write_slave_to_source_in_translator:uav_debugaccess
	wire   [2:0] write_slave_addr_fixer_m0_translator_avalon_universal_master_0_address;       // write_slave_addr_fixer_m0_translator:uav_address -> write_slave_to_source_in_translator:uav_address
	wire         write_slave_addr_fixer_m0_translator_avalon_universal_master_0_read;          // write_slave_addr_fixer_m0_translator:uav_read -> write_slave_to_source_in_translator:uav_read
	wire   [3:0] write_slave_addr_fixer_m0_translator_avalon_universal_master_0_byteenable;    // write_slave_addr_fixer_m0_translator:uav_byteenable -> write_slave_to_source_in_translator:uav_byteenable
	wire         write_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdatavalid; // write_slave_to_source_in_translator:uav_readdatavalid -> write_slave_addr_fixer_m0_translator:uav_readdatavalid
	wire         write_slave_addr_fixer_m0_translator_avalon_universal_master_0_lock;          // write_slave_addr_fixer_m0_translator:uav_lock -> write_slave_to_source_in_translator:uav_lock
	wire         write_slave_addr_fixer_m0_translator_avalon_universal_master_0_write;         // write_slave_addr_fixer_m0_translator:uav_write -> write_slave_to_source_in_translator:uav_write
	wire  [31:0] write_slave_addr_fixer_m0_translator_avalon_universal_master_0_writedata;     // write_slave_addr_fixer_m0_translator:uav_writedata -> write_slave_to_source_in_translator:uav_writedata
	wire   [2:0] write_slave_addr_fixer_m0_translator_avalon_universal_master_0_burstcount;    // write_slave_addr_fixer_m0_translator:uav_burstcount -> write_slave_to_source_in_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (3),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (3),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) write_slave_addr_fixer_m0_translator (
		.clk                    (clock_bridge_out_clk_clk),                                                     //                       clk.clk
		.reset                  (write_slave_addr_fixer_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (write_slave_addr_fixer_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (write_slave_addr_fixer_m0_waitrequest),                                        //                          .waitrequest
		.av_read                (write_slave_addr_fixer_m0_read),                                               //                          .read
		.av_readdata            (write_slave_addr_fixer_m0_readdata),                                           //                          .readdata
		.av_write               (write_slave_addr_fixer_m0_write),                                              //                          .write
		.av_writedata           (write_slave_addr_fixer_m0_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                         //               (terminated)
		.av_byteenable          (4'b1111),                                                                      //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                         //               (terminated)
		.av_begintransfer       (1'b0),                                                                         //               (terminated)
		.av_chipselect          (1'b0),                                                                         //               (terminated)
		.av_readdatavalid       (),                                                                             //               (terminated)
		.av_lock                (1'b0),                                                                         //               (terminated)
		.av_debugaccess         (1'b0),                                                                         //               (terminated)
		.uav_clken              (),                                                                             //               (terminated)
		.av_clken               (1'b1),                                                                         //               (terminated)
		.uav_response           (2'b00),                                                                        //               (terminated)
		.av_response            (),                                                                             //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                         //               (terminated)
		.av_writeresponsevalid  ()                                                                              //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (3),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) write_slave_to_source_in_translator (
		.clk                    (clock_bridge_out_clk_clk),                                                     //                      clk.clk
		.reset                  (write_slave_addr_fixer_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (write_slave_addr_fixer_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (write_slave_to_source_in_address),                                             //      avalon_anti_slave_0.address
		.av_write               (write_slave_to_source_in_write),                                               //                         .write
		.av_writedata           (write_slave_to_source_in_writedata),                                           //                         .writedata
		.av_waitrequest         (write_slave_to_source_in_waitrequest),                                         //                         .waitrequest
		.av_read                (),                                                                             //              (terminated)
		.av_readdata            (32'b11011110101011011101111010101101),                                         //              (terminated)
		.av_begintransfer       (),                                                                             //              (terminated)
		.av_beginbursttransfer  (),                                                                             //              (terminated)
		.av_burstcount          (),                                                                             //              (terminated)
		.av_byteenable          (),                                                                             //              (terminated)
		.av_readdatavalid       (1'b0),                                                                         //              (terminated)
		.av_writebyteenable     (),                                                                             //              (terminated)
		.av_lock                (),                                                                             //              (terminated)
		.av_chipselect          (),                                                                             //              (terminated)
		.av_clken               (),                                                                             //              (terminated)
		.uav_clken              (1'b0),                                                                         //              (terminated)
		.av_debugaccess         (),                                                                             //              (terminated)
		.av_outputenable        (),                                                                             //              (terminated)
		.uav_response           (),                                                                             //              (terminated)
		.av_response            (2'b00),                                                                        //              (terminated)
		.uav_writeresponsevalid (),                                                                             //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                          //              (terminated)
	);

endmodule
