# TCL File Generated by Component Editor 17.1
# Tue Sep 07 10:26:47 CST 2021
# DO NOT MODIFY


# 
# cnn_ctl "cnn_ctl_1.0" v1.0
# lou 2021.09.07.10:26:47
# cnn_ctl_1.0
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cnn_ctl
# 
set_module_property DESCRIPTION cnn_ctl_1.0
set_module_property NAME cnn_ctl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP my_lib
set_module_property AUTHOR lou
set_module_property DISPLAY_NAME cnn_ctl_1.0
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cnn_ctl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cnn_ctl.v VERILOG PATH ip/cnn_ctl/cnn_ctl.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rstn reset_n Input 1


# 
# connection point ddr_in
# 
add_interface ddr_in conduit end
set_interface_property ddr_in associatedClock clock
set_interface_property ddr_in associatedReset reset
set_interface_property ddr_in ENABLED true
set_interface_property ddr_in EXPORT_OF ""
set_interface_property ddr_in PORT_NAME_MAP ""
set_interface_property ddr_in CMSIS_SVD_VARIABLES ""
set_interface_property ddr_in SVD_ADDRESS_GROUP ""

add_interface_port ddr_in ddr_in1 data Output 64


# 
# connection point ddr_out
# 
add_interface ddr_out conduit end
set_interface_property ddr_out associatedClock clock
set_interface_property ddr_out associatedReset reset
set_interface_property ddr_out ENABLED true
set_interface_property ddr_out EXPORT_OF ""
set_interface_property ddr_out PORT_NAME_MAP ""
set_interface_property ddr_out CMSIS_SVD_VARIABLES ""
set_interface_property ddr_out SVD_ADDRESS_GROUP ""

add_interface_port ddr_out ddr_out1 data Output 64


# 
# connection point ddr_w
# 
add_interface ddr_w conduit end
set_interface_property ddr_w associatedClock clock
set_interface_property ddr_w associatedReset reset
set_interface_property ddr_w ENABLED true
set_interface_property ddr_w EXPORT_OF ""
set_interface_property ddr_w PORT_NAME_MAP ""
set_interface_property ddr_w CMSIS_SVD_VARIABLES ""
set_interface_property ddr_w SVD_ADDRESS_GROUP ""

add_interface_port ddr_w ddr_wl data Output 64


# 
# connection point ddr_param
# 
add_interface ddr_param conduit end
set_interface_property ddr_param associatedClock clock
set_interface_property ddr_param associatedReset reset
set_interface_property ddr_param ENABLED true
set_interface_property ddr_param EXPORT_OF ""
set_interface_property ddr_param PORT_NAME_MAP ""
set_interface_property ddr_param CMSIS_SVD_VARIABLES ""
set_interface_property ddr_param SVD_ADDRESS_GROUP ""

add_interface_port ddr_param param data Output 64


# 
# connection point call
# 
add_interface call conduit end
set_interface_property call associatedClock clock
set_interface_property call associatedReset reset
set_interface_property call ENABLED true
set_interface_property call EXPORT_OF ""
set_interface_property call PORT_NAME_MAP ""
set_interface_property call CMSIS_SVD_VARIABLES ""
set_interface_property call SVD_ADDRESS_GROUP ""

add_interface_port call start valid Output 1
add_interface_port call busy stall Input 1


# 
# connection point return
# 
add_interface return conduit end
set_interface_property return associatedClock clock
set_interface_property return associatedReset reset
set_interface_property return ENABLED true
set_interface_property return EXPORT_OF ""
set_interface_property return PORT_NAME_MAP ""
set_interface_property return CMSIS_SVD_VARIABLES ""
set_interface_property return SVD_ADDRESS_GROUP ""

add_interface_port return stall stall Output 1
add_interface_port return done valid Input 1


# 
# connection point as0
# 
add_interface as0 avalon end
set_interface_property as0 addressUnits WORDS
set_interface_property as0 associatedClock clock
set_interface_property as0 associatedReset reset
set_interface_property as0 bitsPerSymbol 8
set_interface_property as0 burstOnBurstBoundariesOnly false
set_interface_property as0 burstcountUnits WORDS
set_interface_property as0 explicitAddressSpan 0
set_interface_property as0 holdTime 0
set_interface_property as0 linewrapBursts false
set_interface_property as0 maximumPendingReadTransactions 0
set_interface_property as0 maximumPendingWriteTransactions 0
set_interface_property as0 readLatency 0
set_interface_property as0 readWaitTime 1
set_interface_property as0 setupTime 0
set_interface_property as0 timingUnits Cycles
set_interface_property as0 writeWaitTime 0
set_interface_property as0 ENABLED true
set_interface_property as0 EXPORT_OF ""
set_interface_property as0 PORT_NAME_MAP ""
set_interface_property as0 CMSIS_SVD_VARIABLES ""
set_interface_property as0 SVD_ADDRESS_GROUP ""

add_interface_port as0 as_address address Input 3
add_interface_port as0 as_write write Input 1
add_interface_port as0 as_read read Input 1
add_interface_port as0 avs_data_waitquest waitrequest Output 1
add_interface_port as0 avs_readdata readdata Output 32
add_interface_port as0 avs_writedata writedata Input 32
set_interface_assignment as0 embeddedsw.configuration.isFlash 0
set_interface_assignment as0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment as0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment as0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ddr_float
# 
add_interface ddr_float conduit end
set_interface_property ddr_float associatedClock clock
set_interface_property ddr_float associatedReset reset
set_interface_property ddr_float ENABLED true
set_interface_property ddr_float EXPORT_OF ""
set_interface_property ddr_float PORT_NAME_MAP ""
set_interface_property ddr_float CMSIS_SVD_VARIABLES ""
set_interface_property ddr_float SVD_ADDRESS_GROUP ""

add_interface_port ddr_float ddr_scale data Output 64

